### ISSUE TITLE
Example usage

### ISSUE THREAD

**Issue by ThinhNguyenHoang** [ramonpeter/MoINN#1]
Hello,

Thanks for the greate  port of the FreIa. But I think there should be some example using the AllInOneBlock or a big model with multple blocks or how to actually combines the blocks and write training loop for them with Keras.

**Comment by ramonpeter** [comment]
Hi,

I could start adding some examples from project we used (parts) of this code. Is there anything not working properly?

**Comment by ThinhNguyenHoang** [comment]
Thanks Sir for your quick response,

I was trying to replicate the [cflow-ad](https://github.com/gudovskiy/cflow-ad) model in tensorflow. I had problems with how to convert their FreIa code (which is used to implement a chains of [conditional coupling layers](https://github.com/gudovskiy/cflow-ad/blob/master/model.py#L46)) to our MoInn framework. 

here is the code snippet (in FreIa):
```
def freia_cflow_head(c, n_feat):
    n_cond = c.condition_vec
    coder = Ff.SequenceINN(n_feat)
    print('CNF coder:', n_feat)
    for k in range(c.coupling_blocks):
        coder.append(Fm.AllInOneBlock, cond=0, cond_shape=(n_cond,), subnet_constructor=subnet_fc, affine_clamping=c.clamp_alpha,
            global_affine_type='SOFTPLUS', permute_soft=True)
    return coder
```
Which I tried to replicate with keras and tensorflow: 
```
def flow_with_condition(config: Config, input_dimension):
    condition_dimension = config.cond_vec_len
    # pool_dimension = input_dimension[-1]
    inp = tuple(input_dimension[:])
    cond = tuple([*inp[:-1],condition_dimension])
    for _ in range(config.coupling_blocks):
        x = AllInOneBlock(inp, [cond],None,subnet_fc,permute_soft=False)
    return x
```
Which would results in error when calling the decoder:

>ValueError: Exception encountered when calling layer "all_in_one_block_3" (type AllInOneBlock).

in user code:

    File "/dmc/thesis-code/sub_models/MoINN/modules/all_in_one_block.py", line 241, in call  *
        a1 = self.subnet(x1c)
    File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 67, in error_handler  **
        raise e.with_traceback(filtered_tb) from None
    File "/usr/local/lib/python3.8/dist-packages/keras/engine/input_spec.py", line 264, in assert_input_compatibility
        raise ValueError(f'Input {input_index} of layer "{layer_name}" is '

    ValueError: Input 0 of layer "sequential_3" is incompatible with the layer: expected shape=(None, 256), found shape=(None, 56, 56, 256)
   
>Call arguments received by layer "all_in_one_block_3" (type AllInOneBlock):
  • x=tf.Tensor(shape=(None, 56, 56, 256), dtype=float32)
  • c=['tf.Tensor(shape=(None, 56, 56, 128), dtype=float32)']
  • rev=False
  • jac=True
 


A few things I have trouble with is:

1. How can you implement something like SequentialINN in the original FreIA framework as I believe it take care of connecting the input and output chaining of the coupling layers. I tried to replicate with Keras.Sequential but I believe it would not take care of adding the condition to the calls of every coupling layers when they are chained (as each coupling layer is called with an input and a condition).
2. I am not sure how the loss is calculated correctly for each of the layers and the subnet used for predicting the parameters in each of the coupling layers. Does keras auto-diff can really take care of this or do we have to calculate the gradient ourself and update them for each of the layer like in the original cflow-ad repos (with GradientTape ?).  
3. when declaring the model of chained AllInOneBlock with condition. How can we pass the condition along with the output from previous block for each AllInOneBlock if the condition is only defined when running the training step (e.g: after calculating some encoding on the input). I tried to create a symbolic placeholder keras.Input(shape=condition_shape) for the condition when declaring the block but it would result in error as we are iterating over the symbolic declaration 

I would be really thankful if you can add some examples on how you would define a model with chained conditional AllInOneBlock together correctly
